### ISSUE TITLE
[Bug]: Upgrade to Laravel 10

### ISSUE THREAD

**Issue by vinhais** [teraone/laravel-cloudflare-zero-trust-middleware#6]
### What happened?

Hello, unfortunately the package is not working in Laravel 10.x :(

`  Problem 1
    - Root composer.json requires teraone/laravel-cloudflare-zero-trust-middleware ^1.0 -> satisfiable by teraone/laravel-cloudflare-zero-trust-middleware[1.0].
    - teraone/laravel-cloudflare-zero-trust-middleware 1.0 requires illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.8] but these were not loaded, likely because it conflicts with another require.`

### How to reproduce the bug

Try installing the package in a project that is on Laravel 10.x.

### Package Version

1.0 

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by sgotre** [comment]
@vinhais  thanks for pointing it out. We will provide an update soon.
